version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Configure environment
          command: |
            bundle install --path "./.vendor"
          working_directory: Argon
      - run: 
          command: bundle exec fastlane scan
          working_directory: Argon
  lint:
    docker:
      - image: dantoml/swiftlint
    steps:
      - checkout
      - run: 
          command: swiftlint
          working_directory: Argon

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - lint:
          requires:
            - build

