version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Run Tests
          command: fastlane scan
          working_directory: Argon
  lint:
    docker:
      - image: dantoml/swiftlint
    steps:
      - checkout
      - run: swiftlint

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - lint